### ISSUE TITLE
Format and validate

### ISSUE THREAD

**Issue by paulyoung** [justinwoo/psc-package2nix#34]
I used to do this:

```sh
  psc-package format
  perl ./scripts/validate.pl
```

What's the recommended way to do that when using this project?

**Comment by justinwoo** [comment]
validate is just a kind of quick and dirty way of chasing down the dependency graph, so you could opt to just verify a single package with `psc-package verify [package]`. Otherwise maybe pp2n could just implement a simpel validate routine itself

**Comment by justinwoo** [comment]
Hmm, actually, if you can do pp2n psc-package2nix then all of the things should be chased down and it should be valid

**Comment by paulyoung** [comment]
OK, thanks for the info!
